### ISSUE TITLE
Erro ao valida CPF com 0 à  esquerda com jquery-form

### ISSUE THREAD

**Issue by bhrunno** [mariohmol/js-brasil#11]
Na versão atual da biblioteca a validação de CPF's : a validação de CPF com 0 à esquerda não está funcionando em utilização com o plugin jquery-form.

Atenciosamente,

**Comment by mariohmol** [comment]
como assim com jquery form? tem algum exemplo?

**Comment by mariohmol** [comment]
adicionei isso aq nos testes e funcionou `expect(validateBr.cpf('090.988.020-44')).to.be.true; `  qual erro acontece do seu lado?

**Comment by mariohmol** [comment]
se tiver mais duvidas pode reabrir
