### ISSUE TITLE
NIT

### ISSUE THREAD

**Issue by mariohmol** [mariohmol/js-brasil#14]
Temos o PIS PASEP funcionando.. nao consegui entender se o NIT é um numero diferente

alguem consegue ajudar?

**Comment by ejkun** [comment]
> O PIS (Programa de Integração Social) e o NIS (também chamado de NIT) são o mesmo número. A diferença é que ele pode ser gerado em duas bases de dados diferentes, por isso têm diferentes nomenclaturas

Fonte: https://valorinveste.globo.com/produtos/servicos-financeiros/noticia/2019/07/19/como-consultar-meu-numero-do-pispasep-nit-e-nis-confira.ghtml

Pesquisando em outros lugares, ensinam que para verificar o NIT é preciso olhar na Carteira de Trabalho, onde está o PIS/PASEP.

Pelo que entendi, o número é igual, a diferença é realmente só a base de dados. Quando precisei do meu NIS eu já tinha o PIS. Mas não funcionava, então tive que ir no CRAS para fazer meu cadastro e obter meu NIS (que é o mesmo número do PIS). Por outro lado, após o primeiro emprego, o PIS é automaticamente convertido em NIS.

Então um número para a várias siglas governar.

**Comment by mariohmol** [comment]
massa.. entao ja q temos o PIS funcionando podemos desconsiderar o NIT pq será igual ne? fechando entao! obrigado!
