### ISSUE TITLE
cpfOrCnpj

### ISSUE THREAD

**Issue by mariohmol** [mariohmol/js-brasil#15]
Field where the user can fill in a CPF or a CNPJ

**Comment by ejkun** [comment]
Acho que isso dá para resumir em:

```js
if (value.length <= 11) {
   return validateCPF(value);
}

return validateCNPJ(value);
```

Basicamente, valida como CPF até o tamanho extrapolar.

**Comment by mariohmol** [comment]
o lance desse é que alem do validar tem q fazer algo pra mascara ser maleável tb.. se consegui fazer um PR desse validate e alguns test cases ia ser massa!

**Comment by ejkun** [comment]
VOu fazer um clone do seu repositório e fazer uns testes. Já já dou uma resposta.

**Comment by ejkun** [comment]
O objetivo é ter validação e máscara, certo?

**Comment by ejkun** [comment]
Consegui, fiz Faker, Validator e Mask.

Pode me guiar em como fazer para gerar os compilados novos? Só fazer npm:dist? Ou vc cuida dessa parte?

**Comment by mariohmol** [comment]
seguinte.. cria um fork desse projeto.. aplica neles.. comita.. e compartilha aq.. a ideia é q se vc ir no Pull Requests.. oc consegue criar um PR enviando essas mudanças pra ca.. se precisar de ajuda podemos fazer um call q te mostro

**Comment by mariohmol** [comment]
foi mal.. agora q vi q ta sem os docs.. vou fazer aq

**Comment by ejkun** [comment]
Blz então. Vou esperar você fazer, Já vou fazer o fork.

**Comment by mariohmol** [comment]
subi os docs
aproveitei pra ja deixar formatado todos os arquivos.. se puder atualizar sua branch

**Comment by mariohmol** [comment]
https://github.com/mariohmol/js-brasil/blob/master/CONTRIBUTING.md

**Comment by mariohmol** [comment]
se tiver ruim ai pra atualziar a branch pode manda da forma como for q mergeio aqui =)

**Comment by ejkun** [comment]
Okay, vou ver se faço essa parte hoje mais tarde. Eu faço o merge daqui e já abro o PR.

**Comment by BianorAraujo** [comment]
Vi que ainda estava aberto esse issue e adicionei a máscara para o value do cpfCnpj com os testes.
Criei o PR #81 para encerrar esse item.
