### ISSUE TITLE
Módulos não encontrados na versão 2.0.0

### ISSUE THREAD

**Issue by rafahsborges** [mariohmol/js-brasil#37]
Estou recebendo esse erro ao utilizar a versão 2.0.0

ERROR in ./node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/estados' in '/var/www/html/node_modules/js-brasil/dist'
ERROR in ./node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/faker' in '/var/www/html/node_modules/js-brasil/dist'
ERROR in ./node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/mask' in '/var/www/html/node_modules/js-brasil/dist'
ERROR in ./node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/placa' in '/var/www/html/node_modules/js-brasil/dist'
ERROR in ./node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/utils' in '/var/www/html/node_modules/js-brasil/dist'
ERROR in ./node_modules/js-brasil/dist/index.js
Module not found: Error: Can't resolve './src/validate' in '/var/www/html/node_modules/js-brasil/dist'

Ao utilizar npm start, npm build, ng serve --aot, ng build --aot, todos produziram o mesmo erro.
Os arquivos realmente não se encontram na pasta. Mas na versão 1.4.3, ou inferior, eles aparecem normalmente.

**Comment by mariohmol** [comment]
ola!! c fala q esses erros tao rolando no ng-brazil?

lançamos a versao pra angular 9 - https://github.com/mariohmol/ng-brazil

tem passado no travis.. entao creio que esteja tudo certo agora
https://travis-ci.org/mariohmol/ng-brazil/builds/623900188

se persistir favor reabrir =)
