### ISSUE TITLE
Validate Data 

### ISSUE THREAD

**Issue by jairochaves2** [mariohmol/js-brasil#41]
**Descrição do Problema**

Ao usar o comando `validateBr.data(paciente.dtNascimento);` com o `paciente.dtNascimento` vazio é retornado o valor `true`.

Testando o valor `validateBr.data("");` também é retornado o valor true.
Acredito que deveria ser retornado o valor `false` para datas vazias.

**Comment by mariohmol** [comment]
uhmm boa! fiz o fix na 2.0.6
