### ISSUE TITLE
A função validateBr.cpfcnpj está sempre retornando true, não possui nenhuma verificação

### ISSUE THREAD

**Issue by lucaspelle1909** [mariohmol/js-brasil#47]
Entrando no arquivo js-brasil, há a seguinte função:

```
exports.validate_cpf = validate_cpf;
function validate_cpfcnpj(number) {
    return true;
}
```

**Comment by mariohmol** [comment]
sim.. ainda nao foi implementado
https://github.com/mariohmol/js-brasil/issues/15

mas eu comitei essa funcao p ter o validate pelo menos

se tiver interesse em ajudar =)
