### ISSUE TITLE
Vue Failed to compile.

### ISSUE THREAD

**Issue by samirissa00** [mariohmol/js-brasil#48]
Depois de instalar com sucesso via npm no projeto 
dá um erro de compilação !!

Failed to compile.

./node_modules/vue-brazil/src/index.js
Module not found: Error: [CaseSensitivePathsPlugin] `c:\Users\samir\Dropbox\Vue_projects\vue-material-dashboard-pro-v1.3.2\node_modules\vue-brazil\src\filter\JSBrazilFilter.js` does not match the corresponding path on disk `JsBrazilFilter.js`.

**Comment by mariohmol** [comment]
c consegue montar um demo no stackblitz?
https://github.com/mariohmol/vue-brazil/issues/9

Nao uso vue, fiz isso mais pra um amigo.. mas se puder ajudar!

Criei a issue no repo do vue pra fica mais facil o follow
https://github.com/mariohmol/vue-brazil/issues/10

**Comment by mariohmol** [comment]
@Ofamosomario

**Comment by mariohmol** [comment]
fix realizado no repo https://github.com/mariohmol/vue-brazil
