### ISSUE TITLE
error with ng build --prod

### ISSUE THREAD

**Issue by andrejm7** [mariohmol/js-brasil#56]
error with ng build --prod in version 2.3.2

ERROR in node_modules/js-brasil/src/utils.ts:2:27 - error TS2307: Cannot find module 'interfaces' or its corresponding type declarations.

2 import { BigObject } from "interfaces";
                            ~~~~~~~~~~~~
node_modules/js-brasil/src/iptu/mask.ts:1:37 - error TS2307: Cannot find module 'interfaces' or its corresponding type declarations.

1 import { BigObject, MaskType } from "interfaces";
                                      ~~~~~~~~~~~~
node_modules/js-brasil/src/iptu/create.ts:3:27 - error TS2307: Cannot find module 'interfaces' or its corresponding type declarations.

3 import { BigObject } from "interfaces";
                            ~~~~~~~~~~~~
node_modules/js-brasil/src/iptu/validate.ts:3:27 - error TS2307: Cannot find module 'interfaces' or its corresponding type declarations.

**Comment by andrejm7** [comment]
Oi Mario se puder agilizar a correção.. eu agradeço

**Comment by andrejm7** [comment]
???????

**Comment by mariohmol** [comment]
oi.. ja subi a correcao.. ta na ultima versao.. nao?

**Comment by andrejm7** [comment]
Estou sim.. .mas tá com erro ainda nos imports

**Comment by andrejm7** [comment]
import { BigObject } from "interfaces";


Aqui o angular acusa erro...

O correto seria assim

import { BigObject } from "./interfaces";

Tem mais uns 5.. 6 lugares com esse errinho de import

**Comment by mariohmol** [comment]
Corrigido v2.3.3, checa ai pf

**Comment by thiagoborba** [comment]
Bom dia, Mario!

O erro ainda persiste:


`/home/thiago/Projetos/sicredi/vehicle-insurance-web/node_modules/js-brasil/src/utils.ts
TypeScript error in /home/thiago/Projetos/sicredi/vehicle-insurance-web/node_modules/js-brasil/src/utils.ts(2,27):
Cannot find module 'interfaces' or its corresponding type declarations.  TS2307

    1 | import { ESTADOS_SIGLA } from "./estados";
  > 2 | import { BigObject } from "interfaces";
      |                           ^
    3 | 
    4 | export function isPresent(obj: any): boolean {
    5 |   return obj !== undefined && obj !== null;`

Estou com a versão "js-brasil": "^2.3.4",

**Comment by andrejm7** [comment]
Consigo testar a noite.. mas acho que vai dar esse mesmo erro ai do amigo.. @mariohmol

**Comment by mariohmol** [comment]
foi mal pessoal.. achei q todos os imports estavam com '  , dai já converti todod que estava de " para ' e localizei todos os interfaces tb.

v2.3.5

**Comment by andrejm7** [comment]
gente o que está ocorrendo?

![image](https://user-images.githubusercontent.com/13546247/95139509-000d3180-0743-11eb-915f-401ee81953d9.png)


estou na ultima versão.... v2.3.6

**Comment by andrejm7** [comment]
na lib não tem mais a pasta src... @mariohmol

**Comment by mariohmol** [comment]
recebí um PR #60 e realmente estava receoso de tirar o src do npm.. coloquei de volta.. vê a 2.3.7
