### ISSUE TITLE
Inscrição Estadual valida apenas estado de MG

### ISSUE THREAD

**Issue by Leonardofsm** [mariohmol/js-brasil#57]
Estou implementando a máscara e o validator para inscrição estadual. Porém gerando IE para testar, ele só valida se eu digitar
todos números iguais (ex: 111.111.111, 222.222.222 e assim por diante, para todos estados). Os IE gerados para cara estado que ele implementa a mascara, retorna um false... exceto o estado de MG.
Testei neste link se era algo na implementação: https://stackblitz.com/edit/ng-brazil?file=src%2Fapp%2Fapp.component.html
porém também só valida o estado de MG, os outros não.

Seria algo na forma que implementei ou na lib ?

**Comment by mariohmol** [comment]
Saca só esses tests:

https://github.com/mariohmol/js-brasil/blob/master/test/validate.ts#L193

Em tese ele está validando, só se existe um bug no ng...

os numeros q oc tem testado estao contemplados nesses tests?

**Comment by Leonardofsm** [comment]
Usei os exemplos desse teste porém não rolou tbm. 

Então nesse link que mandei, ele gera a mascara e da uma IE de exemplo válida, porém no resultado retorna 'Errors Found: inscricaoestadual true' para a maioria dos estados exceto MG (não consegui testar todos). 

Por gerar a mascara certinho conforme o estado que eu passo, achei que poderia ser algo no ng. (estou começando faz pouco tempo, então não tenho muita certeza e também sugestão de uq pode ser).

![image](https://user-images.githubusercontent.com/37203246/95137193-f2a17880-073d-11eb-9c22-4e5dc27ff779.png)

**Comment by mariohmol** [comment]
Essa inscrição estadual deu como incorreta no algoritmo pro DF...

tem certeza que este numero é real?
