### ISSUE TITLE
Nova I.E do Distrito Federal

### ISSUE THREAD

**Issue by joseAAlexandre** [mariohmol/js-brasil#61]
Foi liberado no mês 09/2020 um novo padrão para geração de inscrição estadual do D.F, as novas empresas estão cadastradas com a inicial 08 antigamente era fixo 07.

![image](https://user-images.githubusercontent.com/70344242/95505280-79e02d80-0984-11eb-8f33-3f2742fec4cd.png)

**Comment by mariohmol** [comment]
obrigado!

testa a v2.3.8

**Comment by joseAAlexandre** [comment]
Funcionou, obrigado.
