### ISSUE TITLE
Not all code paths return a value

### ISSUE THREAD

**Issue by guilhermelima89** [mariohmol/js-brasil#62]
Salve Mario, tranquilo?
Se você criar um novo projeto angular utilizando "ng new [nome_do_projeto] --strict" ele cria alguns parâmetros a mais no arquivo tsconfig.json sendo um deles "noImplicitReturns": true que me retorna dois erros:

1) js-brasil/src/mask.ts

![image](https://user-images.githubusercontent.com/60924228/108519268-3e495e80-72a8-11eb-934e-75dd04ee083e.png)

2) js-brasil/src/iptu/validate.ts

![image](https://user-images.githubusercontent.com/60924228/108519346-4c977a80-72a8-11eb-91a1-8a9fb2b121bf.png)

Obs: Acredito que no Angular 12 essa opção será ativada por padrão.

Cenário: criei o projeto, importei os dois módulos no app.module e importei a mask no app.component, no build apresenta erro.

**Comment by mariohmol** [comment]
Obrigado pelo alerta!

sugestão de fix?

**Comment by mariohmol** [comment]
O fix está na última versao.. pode atualizar o js-brasil e o ng-brasil

vlw!
