### ISSUE TITLE
textmask com erro no modo strict

### ISSUE THREAD

**Issue by guilhermelima89** [mariohmol/js-brasil#63]
Salve Mario, tranquilo?
Atualizei os pacotes com a última versão porém agora estou com erro na máscara quando o "strictTemplates" é TRUE no arquivo "tsconfig".

Mensagem de erro: 
Type 'Function | MaskType | (string | RegExp)[] | undefined' is not assignable to type 'false | (string | RegExp)[] | ((raw: string) => (string | RegExp)[])'.
Type 'undefined' is not assignable to type 'false | (string | RegExp)[] | ((raw: string) => (string | RegExp)[])'.ngtsc(2322)
![image](https://user-images.githubusercontent.com/60924228/109151663-3a568a00-7749-11eb-9e0f-8edc8a7a0884.png)

Se eu desativo, consigo utilizar normalmente, porém o próprio VsCode fica aparecendo um alerta toda hora.
![image](https://user-images.githubusercontent.com/60924228/109150054-1abe6200-7747-11eb-8bb1-db210ccbc34a.png)

Tscondig
![image](https://user-images.githubusercontent.com/60924228/109148960-b353e280-7745-11eb-9447-0510aee1d52c.png)

Html
![image](https://user-images.githubusercontent.com/60924228/109147801-36743900-7744-11eb-8f2a-135db496ef4d.png)

App component
![image](https://user-images.githubusercontent.com/60924228/109147761-29efe080-7744-11eb-8eb7-6ba490789a16.png)

Módulo
![image](https://user-images.githubusercontent.com/60924228/109147723-1b092e00-7744-11eb-9c57-fb8cdb5bcb22.png)

"A partir da versão 12, removeremos o prompt do modo estrito e todos os novos projetos terão essas configurações habilitadas desde o início."

referência: https://blog.angular.io/with-best-practices-from-the-start-d64881a16de8

Observação: eu ainda não encontrei um fix :D

**Comment by mariohmol** [comment]
angular 12 ta em beta ainda ne?

atualizei o repo do ng-brazil pro ang 11, adicionei essa prop e continua funcionando normal...

atualizei o plugin pra 2.4.2 com ang11

**Comment by mariohmol** [comment]
essa ultima rolou ai?

**Comment by guilhermelima89** [comment]
Olá Mario, desculpa pela demora.

Infelizmente não funcionou :

Error: src/app/app.component.html:5:23 - error TS2322: Type 'Function | MaskType | (string | RegExp)[] | undefined' is not assignable to type 'false | (string | RegExp)[] | ((raw: string) => (string | RegExp)[])'. 
  Type 'undefined' is not assignable to type 'false | (string | RegExp)[] | ((raw: string) => (string | RegExp)[])'.

5   [textMask]="{ mask: MASKS.cpf.textMask }"

Estou utilizando a versão 11 do angular, porém estou criando um projeto da seguinte maneira

1) ng new AngularTeste --strict
2) depois a instalação dos pacotes
3) depois importação no módulos
4) depois a importação nos componentes

Repositório com o erro
https://github.com/guilhermelima89/angular-strict

Abraços

**Comment by guilhermelima89** [comment]
alguma novidade?

**Comment by mariohmol** [comment]
Eu adicionei no repo essa conf e nao subiu esse erro..  vc tem ideia de como arrumar?

**Comment by mariohmol** [comment]
Instala o novo jsbrasil, acho que arrumei

**Comment by mariohmol** [comment]
subi uma versao nova do ng-brazil tb com melhorias, ang11 e removi warnings..
