### ISSUE TITLE
CNH não funciona

### ISSUE THREAD

**Issue by joaopedr0vieira** [mariohmol/js-brasil#65]
**Describe the bug**

**To Reproduce**
Alguns cnh's válidos estão resultando em `false`, exemplo: **59796888141**

**Expected behavior**
Deveria validar como true

**Desktop (please complete the following information):**
próprio site http://geradorbrasileiro.com/cnh.html

**Comment by mariohmol** [comment]
mas ai o lance.. como podemos confirmar q esse numero está correto?

**Comment by mariohmol** [comment]
vc está certo!
corrigido!
obrigado

**Comment by joaopedr0vieira** [comment]
Não sei se o site (http://geradorbrasileiro.com/cnh.html) foi atualizado já, mas ainda não tá funcionando. Eu estou testando com base nesse gerador (https://www.4devs.com.br/gerador_de_cnh) e nesse validador (https://www.4devs.com.br/validador_cnh) os dados gerados pelo **js-brasil** não são válidos no **4devs** e vice versa.

**Comment by joaopedr0vieira** [comment]
Além de minha própria cnh ser validada como falsa.

**Comment by mariohmol** [comment]
o site nao estava atualizado.. achei q estava usando o codigo.. atualizei la!! obrigado pelo lembrete
