### ISSUE TITLE
CNHs verdadeiros  aparecendo como inválido

### ISSUE THREAD

**Issue by pscordeiro** [mariohmol/js-brasil#70]
Estou com alguns CNHs específicos, que existem no sistema do Detran, porém aparecem como inválidos em todos os validadores que testei até o momento, inclusive o do geradorbrasileiro.com

Já tentei entender se tem algum padrão entre eles, mas não obtive nada conclusivo, por serem dados sensíveis de clientes existentes não posso passar o número aqui, mas se alguém um dia ver isso aqui, pode entrar em contato comigo que irei passar os números já que gostaria muito de entender o que tem de diferente nesses CNHs.

**Comment by mariohmol** [comment]
De fato houveram mais mudanças e parece que as novas carteiras estão sem o modulo11 ou com algum algorítmo proprietário do DETRAN, portanto foi alterado para nao utilizar mais a validacao

aproveitei para incluir tb os demais itens da CNH (espelho, estadual, segurança)
