### ISSUE TITLE
Nova regra de IE para o estado de GO

### ISSUE THREAD

**Issue by joseAAlexandre** [mariohmol/js-brasil#73]
**Describe the bug**
Em algum momento desse ano foi atualizado a validação de inscrição estadual do estado de GO e acabei pegando um caso que a validação está retornando como false, mesmo sendo uma IE valida.

**To Reproduce**
Fazer a validação de IE GO 20.024.521-0

**Expected behavior**
Deveria retornar como sucesso.

**Screenshots**
![image](https://github.com/mariohmol/js-brasil/assets/70344242/06b31751-53d0-4248-9e22-b07329a79173)

**Additional context**
Aqui pode ser encontrada a nova regra de validação de IE de GO - [http://www.sintegra.gov.br/Cad_Estados/cad_GO.html](url)

**Comment by joseAAlexandre** [comment]
@mariohmol Quando possível conferir o pull request e informar se será possível gerar uma versão.

**Comment by mariohmol** [comment]
thanks js-brasil@2.6.1
