### ISSUE TITLE
Dependências Dev em Prod

### ISSUE THREAD

**Issue by kimtiago** [mariohmol/js-brasil#75]
Eu não sou expert em nodejs ainda, estou aprendendo bastante nos últimos meses, então se eu estiver falando alguma besteira, por favor me corrija. 

Com a versão 2.6.0, vc adicionou várias dependências no projeto que, a meu ver, seriam de desenvolvimento.

O que está me incomodando é essa lib do Gulp que é bem antiga, ela tem zilhões de dependências e tambem muito antigas com diversas falhas de segurança criticas, e isso está indo pro build do meu projeto.

Não seria o caso de colocar o Gulp e outras ali para desenvolvimento?

**Comment by mariohmol** [comment]
Ola!

obrigado pela sugestao..
sim eu havia feito uma limpa ja do faker.. pra otimizar essa lib..

se puder criar um PR seria otimo

obrigado

**Comment by mariohmol** [comment]
Dependencias removidas https://github.com/mariohmol/js-brasil/blob/master/package.json#L38

Obrigado
