### ISSUE TITLE
validação de inscrição estadual do Pará

### ISSUE THREAD

**Issue by ddanielsantos** [mariohmol/js-brasil#83]
Inscrições Estaduais do Pará agora podem começar com outros prefixos além do `15`

fontes:
http://www.sintegra.gov.br/Cad_Estados/cad_PA.html
https://tucurui.portaldacidade.com/noticias/economia/sefa-implementa-nova-numeracao-para-inscricao-estadual-no-para-3335
https://www.roraimanarede.com.br/noticia/118791/inscricoes-estaduais-da-sefa-para-agora-podem-iniciar-com-numeracao-75

**Comment by mariohmol** [comment]
Obrigado js-brasil@2.6.4
